# Generated by Django 5.2.17 on 2026-09-25 03:08

import django.core.validators
import django.db.models.deletion
import estoque.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('codigo', models.CharField(max_length=40, unique=True, verbose_name='código')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('ativa', models.BooleanField(default=True)),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sublocalizacoes', to='estoque.localizacao', verbose_name='localização superior')),
            ],
            options={
                'verbose_name': 'localização',
                'verbose_name_plural': 'localizações',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('codigo', models.CharField(max_length=40, unique=True, verbose_name='código interno')),
                ('identificador', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(db_index=True, max_length=200, verbose_name='nome / descrição')),
                ('marca', models.CharField(blank=True, db_index=True, max_length=80)),
                ('aplicacao', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='modelo / aplicação')),
                ('ano_inicial', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('ano_final', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('motor', models.CharField(blank=True, max_length=80, verbose_name='motor / aplicação')),
                ('posicao', models.CharField(blank=True, max_length=80, verbose_name='lado / posição')),
                ('condicao', models.CharField(choices=[('usada', 'Usada'), ('testada', 'Usada e testada'), ('recondicionada', 'Recondicionada'), ('reparo', 'Necessita reparo')], default='usada', max_length=20, verbose_name='condição')),
                ('custo', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preço de venda')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('reservada', 'Reservada'), ('vendida', 'Vendida'), ('baixada', 'Baixada / indisponível')], db_index=True, default='disponivel', max_length=20)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pecas', to='estoque.categoria')),
                ('localizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pecas', to='estoque.localizacao', verbose_name='localização')),
                ('veiculo_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pecas', to='veiculos.veiculo', verbose_name='veículo de origem')),
            ],
            options={
                'verbose_name': 'peça',
                'verbose_name_plural': 'peças',
                'ordering': ['nome', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='FotoPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('imagem', models.ImageField(upload_to=estoque.models.caminho_foto, validators=[estoque.models.validar_tamanho_foto])),
                ('legenda', models.CharField(blank=True, max_length=160)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='estoque.peca')),
            ],
            options={
                'verbose_name': 'foto da peça',
                'verbose_name_plural': 'fotos da peça',
                'ordering': ['ordem', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='localizacao',
            constraint=models.CheckConstraint(condition=models.Q(('pk', models.F('pai_id')), _negated=True), name='localizacao_nao_e_proprio_pai'),
        ),
        migrations.AddIndex(
            model_name='peca',
            index=models.Index(fields=['status', 'categoria'], name='peca_status_categoria_idx'),
        ),
        migrations.AddConstraint(
            model_name='peca',
            constraint=models.CheckConstraint(condition=models.Q(('custo__gte', 0)), name='peca_custo_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='peca',
            constraint=models.CheckConstraint(condition=models.Q(('preco_venda__gte', 0)), name='peca_preco_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='peca',
            constraint=models.CheckConstraint(condition=models.Q(('ano_inicial__isnull', True), ('ano_inicial__range', (1900, 2100)), _connector='OR'), name='peca_ano_inicial_valido'),
        ),
        migrations.AddConstraint(
            model_name='peca',
            constraint=models.CheckConstraint(condition=models.Q(('ano_final__isnull', True), ('ano_final__range', (1900, 2100)), _connector='OR'), name='peca_ano_final_valido'),
        ),
        migrations.AddConstraint(
            model_name='peca',
            constraint=models.CheckConstraint(condition=models.Q(('ano_inicial__isnull', True), ('ano_final__isnull', True), ('ano_final__gte', models.F('ano_inicial')), _connector='OR'), name='peca_intervalo_anos_valido'),
        ),
        migrations.AddConstraint(
            model_name='peca',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['disponivel', 'reservada']), _negated=True), ('quantidade__gt', 0), _connector='OR'), name='peca_ativa_tem_quantidade'),
        ),
        migrations.AddConstraint(
            model_name='peca',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'vendida'), _negated=True), ('quantidade', 0), _connector='OR'), name='peca_vendida_sem_saldo'),
        ),
    ]
