# Generated by Django 5.2.17 on 2026-09-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_categorias_iniciais'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE SEQUENCE estoque_peca_codigo_seq",
            "DROP SEQUENCE estoque_peca_codigo_seq",
        ),
        migrations.AlterField(
            model_name='peca',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=40, unique=True, verbose_name='código interno'),
        ),
    ]
