# Generated by Django 5.2.17 on 2026-09-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_peca_codigo'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE SEQUENCE estoque_localizacao_codigo_seq",
            "DROP SEQUENCE estoque_localizacao_codigo_seq",
        ),
        migrations.RunSQL(
            "SELECT setval('estoque_localizacao_codigo_seq', COALESCE((SELECT MAX(substring(codigo from '[0-9]+$')::bigint) FROM estoque_localizacao WHERE codigo ~ '^LOC-[0-9]+$'), 0) + 1, false)",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='localizacao',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=40, unique=True, verbose_name='código'),
        ),
    ]
