# Generated by Django 5.2.17 on 2026-10-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_localizacao_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peca',
            name='condicao',
            field=models.CharField(choices=[('nova', 'Novo'), ('usada', 'Usada'), ('testada', 'Usada e testada'), ('recondicionada', 'Recondicionada'), ('reparo', 'Necessita reparo')], default='usada', max_length=20, verbose_name='condição'),
        ),
    ]
