# Generated by Django 5.2.17 on 2026-10-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_alter_peca_condicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='compativel',
            field=models.TextField(blank=True, help_text='Informe veículos, modelos ou outras aplicações compatíveis.', verbose_name='Compatível'),
        ),
        migrations.AddField(
            model_name='peca',
            name='postada_online',
            field=models.BooleanField(default=False, help_text='Marque quando a peça estiver anunciada no Mercado Livre, Shopee, OLX ou outros canais.', verbose_name='Publicada para venda online'),
        ),
    ]
