# Generated by Django 5.2.17 on 2026-09-25 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('acao', models.CharField(max_length=80)),
                ('objeto', models.CharField(max_length=120)),
                ('dados', models.JSONField(default=dict)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evento de auditoria',
                'verbose_name_plural': 'auditoria',
                'ordering': ['-criado_em', '-pk'],
            },
        ),
    ]
