# Generated by Django 5.2.17 on 2026-09-30 00:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_proteger_historico'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('unica', models.BooleanField(default=True, editable=False, unique=True)),
                ('razao_social', models.CharField(blank=True, max_length=200, verbose_name='razão social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, verbose_name='nome fantasia')),
                ('documento', models.CharField(blank=True, max_length=20, verbose_name='CNPJ/CPF')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=30, verbose_name='inscrição estadual')),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='endereço')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, verbose_name='estado')),
                ('logo', models.ImageField(blank=True, upload_to=core.models.caminho_logo_empresa)),
            ],
            options={
                'verbose_name': 'configuração da empresa',
                'verbose_name_plural': 'configurações da empresa',
                'default_permissions': ('view', 'change'),
                'constraints': [models.CheckConstraint(condition=models.Q(('unica', True)), name='configuracao_empresa_unica_true')],
            },
        ),
    ]
