# Generated by Django 5.2.17 on 2026-09-25 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caixa', '0003_movimentocaixa_chave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('fornecedor', models.CharField(max_length=160, verbose_name='fornecedor / favorecido')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vencimento', models.DateField()),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], default='pendente', max_length=12)),
                ('pago_em', models.DateField(blank=True, null=True)),
                ('forma_nome', models.CharField(blank=True, max_length=80)),
                ('motivo_cancelamento', models.TextField(blank=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('movimento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='caixa.movimentocaixa')),
                ('pago_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conta a pagar',
                'verbose_name_plural': 'contas a pagar',
                'ordering': ['vencimento', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='conta_valor_positivo')],
            },
        ),
    ]
