# Generated by Django 5.2.17 on 2026-09-25 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
        ('vendas', '0004_promissoria_inicial_e_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Academia e Atividades Físicas', 'Academia e Atividades Físicas'), ('Água e Saneamento', 'Água e Saneamento'), ('Alimentação', 'Alimentação'), ('Aluguel', 'Aluguel'), ('Animais de Estimação', 'Animais de Estimação'), ('Assinaturas e Mensalidades', 'Assinaturas e Mensalidades'), ('Babá e Cuidador', 'Babá e Cuidador'), ('Benefícios de Funcionários', 'Benefícios de Funcionários'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Cartório e Autenticações', 'Cartório e Autenticações'), ('Combustível', 'Combustível'), ('Comissões', 'Comissões'), ('Compras de Mercadorias', 'Compras de Mercadorias'), ('Condomínio', 'Condomínio'), ('Consórcio', 'Consórcio'), ('Consultoria', 'Consultoria'), ('Contabilidade', 'Contabilidade'), ('Cursos e Treinamentos', 'Cursos e Treinamentos'), ('Decoração', 'Decoração'), ('Despesas Administrativas', 'Despesas Administrativas'), ('Despesas Bancárias', 'Despesas Bancárias'), ('Despesas Escolares', 'Despesas Escolares'), ('Despesas com Funcionários', 'Despesas com Funcionários'), ('Despesas Jurídicas', 'Despesas Jurídicas'), ('Doações e Contribuições', 'Doações e Contribuições'), ('Educação', 'Educação'), ('Eletrodomésticos', 'Eletrodomésticos'), ('Empréstimos', 'Empréstimos'), ('Energia Elétrica', 'Energia Elétrica'), ('Equipamentos', 'Equipamentos'), ('Estacionamento', 'Estacionamento'), ('Eventos', 'Eventos'), ('Farmácia e Medicamentos', 'Farmácia e Medicamentos'), ('Financiamento de Imóvel', 'Financiamento de Imóvel'), ('Financiamento de Veículo', 'Financiamento de Veículo'), ('Financiamentos', 'Financiamentos'), ('Fornecedores', 'Fornecedores'), ('Fretes e Entregas', 'Fretes e Entregas'), ('Gás', 'Gás'), ('Higiene Pessoal', 'Higiene Pessoal'), ('Hospedagem', 'Hospedagem'), ('Impostos e Tributos', 'Impostos e Tributos'), ('Internet', 'Internet'), ('IPTU', 'IPTU'), ('IPVA', 'IPVA'), ('Jardinagem', 'Jardinagem'), ('Lazer e Entretenimento', 'Lazer e Entretenimento'), ('Licenças e Alvarás', 'Licenças e Alvarás'), ('Limpeza e Conservação', 'Limpeza e Conservação'), ('Manutenção de Computadores', 'Manutenção de Computadores'), ('Manutenção de Equipamentos', 'Manutenção de Equipamentos'), ('Manutenção de Imóveis', 'Manutenção de Imóveis'), ('Manutenção Residencial', 'Manutenção Residencial'), ('Manutenção de Veículos', 'Manutenção de Veículos'), ('Marketing', 'Marketing'), ('Material de Construção', 'Material de Construção'), ('Material de Escritório', 'Material de Escritório'), ('Material de Limpeza', 'Material de Limpeza'), ('Materiais de Consumo', 'Materiais de Consumo'), ('Móveis', 'Móveis'), ('Obras e Reformas', 'Obras e Reformas'), ('Parcelamentos', 'Parcelamentos'), ('Pedágios', 'Pedágios'), ('Pensão Alimentícia', 'Pensão Alimentícia'), ('Plano de Saúde', 'Plano de Saúde'), ('Presentes', 'Presentes'), ('Prestadores de Serviços', 'Prestadores de Serviços'), ('Produtos de Limpeza', 'Produtos de Limpeza'), ('Publicidade e Propaganda', 'Publicidade e Propaganda'), ('Refeições', 'Refeições'), ('Roupas e Calçados', 'Roupas e Calçados'), ('Salários', 'Salários'), ('Saúde', 'Saúde'), ('Segurança', 'Segurança'), ('Seguros', 'Seguros'), ('Seguro Residencial', 'Seguro Residencial'), ('Seguro de Veículo', 'Seguro de Veículo'), ('Serviços Domésticos', 'Serviços Domésticos'), ('Serviços de Terceiros', 'Serviços de Terceiros'), ('Software e Sistemas', 'Software e Sistemas'), ('Streaming', 'Streaming'), ('Supermercado', 'Supermercado'), ('Taxas Bancárias', 'Taxas Bancárias'), ('Taxas e Tarifas', 'Taxas e Tarifas'), ('Telefonia', 'Telefonia'), ('Transporte', 'Transporte'), ('TV por Assinatura', 'TV por Assinatura'), ('Uniformes e EPIs', 'Uniformes e EPIs'), ('Utensílios Domésticos', 'Utensílios Domésticos'), ('Veículos', 'Veículos'), ('Viagens', 'Viagens'), ('Outros', 'Outros')], max_length=80, verbose_name='categoria'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='data_programada',
            field=models.DateField(blank=True, null=True, verbose_name='data programada de pagamento'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='forma_prevista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vendas.formapagamento', verbose_name='forma de pagamento'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='tipo_conta',
            field=models.CharField(blank=True, choices=[('residencial', 'Residencial'), ('empresa', 'Empresa')], max_length=12, verbose_name='tipo de conta'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, verbose_name='descrição'),
        ),
    ]
