# Generated by Django 5.2.17 on 2026-09-25 18:56

import contas.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_contapagar_categoria_contapagar_data_programada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, storage=contas.models.armazenamento_comprovantes, upload_to=contas.models.caminho_comprovante)),
                ('nome_arquivo', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True, max_length=2000)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anexos', to='contas.contapagar')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em', '-pk'],
            },
        ),
    ]
