# Generated by Django 5.2.17 on 2026-09-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_anexoconta'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='pix_copia_cola',
            field=models.TextField(blank=True, help_text='Cole o código de pagamento fornecido pelo recebedor.', max_length=4096, verbose_name='PIX Copia e Cola'),
        ),
    ]
