# Generated by Django 5.2.17 on 2026-09-30 21:55

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


def preservar_historico(apps, schema_editor):
    contas = apps.get_model('contas', 'ContaPagar').objects.using(schema_editor.connection.alias)
    # Apenas inicializa os novos campos; valores, datas e comprovantes antigos permanecem intactos.
    contas.update(valor_original=models.F('valor'))
    contas.filter(status='paga').update(valor_pago=models.F('valor'))
    formas = apps.get_model('vendas', 'FormaPagamento').objects.using(schema_editor.connection.alias)
    for nome, dinheiro in [('Boleto', False), ('PIX', False), ('Transferência', False), ('Cartão', False),
                            ('Dinheiro', True), ('Débito automático', False), ('Outros', False)]:
        if not formas.filter(nome__iexact=nome).exists():
            formas.create(nome=nome, dinheiro=dinheiro, ativa=True, promissoria=False)


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0003_movimentocaixa_chave'),
        ('contas', '0004_contapagar_pix_copia_cola'),
        ('vendas', '0007_boleto_parcelado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagar', name='pago_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='contas_pagas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PagamentoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('forma_nome', models.CharField(max_length=80)),
                ('origem', models.CharField(choices=[('externo', 'Fora do caixa'), ('caixa', 'Caixa')], max_length=10)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='anexoconta',
            name='tipo',
            field=models.CharField(choices=[('cobranca', 'Documento da cobrança'), ('comprovante', 'Comprovante de pagamento'), ('outro', 'Documento anterior / outro')], default='outro', max_length=12),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='acrescimos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='outros acréscimos'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='centro_custo',
            field=models.CharField(blank=True, max_length=100, verbose_name='centro de custo'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='competencia',
            field=models.DateField(blank=True, null=True, verbose_name='competência'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='emissao',
            field=models.DateField(blank=True, null=True, verbose_name='data de emissão'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='frequencia',
            field=models.CharField(blank=True, choices=[('semanal', 'Semanal'), ('mensal', 'Mensal'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=12),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='juros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='lote',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='modo',
            field=models.CharField(choices=[('unica', 'Conta única'), ('recorrente', 'Recorrente'), ('parcelada', 'Parcelada')], default='unica', max_length=12),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='multa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=100, verbose_name='número do documento'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='parcela',
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='subcategoria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='total_parcelas',
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='valor_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor original'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='status',
            field=models.CharField(choices=[('pendente', 'Aguardando'), ('parcial', 'Parcialmente paga'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], default='pendente', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='contapagar',
            constraint=models.UniqueConstraint(fields=('lote', 'parcela'), name='conta_lote_parcela_unica'),
        ),
        migrations.AddConstraint(
            model_name='contapagar',
            constraint=models.CheckConstraint(condition=models.Q(('acrescimos__gte', 0), ('desconto__gte', 0), ('juros__gte', 0), ('multa__gte', 0), ('valor_pago__gte', 0), ('valor_pago__lte', models.F('valor'))), name='conta_valores_validos'),
        ),
        migrations.AddConstraint(
            model_name='contapagar',
            constraint=models.CheckConstraint(condition=models.Q(('valor_original__isnull', True), ('valor', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('valor_original'), '-', models.F('desconto')), '+', models.F('juros')), '+', models.F('multa')), '+', models.F('acrescimos'))), _connector='OR'), name='conta_total_consistente'),
        ),
        migrations.AddField(
            model_name='pagamentoconta',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='contas.contapagar'),
        ),
        migrations.AddField(
            model_name='pagamentoconta',
            name='forma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendas.formapagamento'),
        ),
        migrations.AddField(
            model_name='pagamentoconta',
            name='movimento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='caixa.movimentocaixa'),
        ),
        migrations.AddField(
            model_name='pagamentoconta',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anexoconta',
            name='pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anexos', to='contas.pagamentoconta'),
        ),
        migrations.AddConstraint(
            model_name='pagamentoconta',
            constraint=models.CheckConstraint(condition=models.Q(('desconto__gte', 0), ('juros__gte', 0), ('valor__gt', 0)), name='pagamento_conta_valores_validos'),
        ),
        migrations.RunPython(preservar_historico, migrations.RunPython.noop),
    ]
