# Generated by Django 5.2.17 on 2026-09-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_cadastro_financeiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=60, verbose_name='código de barras'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='linha_digitavel',
            field=models.CharField(blank=True, max_length=60, verbose_name='linha digitável'),
        ),
    ]
