# Generated by Django 5.2.17 on 2026-10-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_contapagar_codigo_barras_contapagar_linha_digitavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagar',
            name='frequencia',
            field=models.CharField(blank=True, choices=[('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('dias', 'Intervalo em dias')], max_length=12),
        ),
    ]
