# Generated by Django 5.2.17 on 2026-09-25 04:06

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caixa', '0001_initial'),
        ('clientes', '0001_initial'),
        ('estoque', '0004_alter_localizacao_codigo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('dinheiro', models.BooleanField(default=False, verbose_name='movimenta dinheiro físico')),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'forma de pagamento',
                'verbose_name_plural': 'formas de pagamento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente_nome', models.CharField(blank=True, max_length=160)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('concluida', 'Concluída'), ('parcial', 'Devolução parcial'), ('devolvida', 'Devolvida'), ('cancelada', 'Cancelada')], default='concluida', max_length=20)),
                ('motivo_cancelamento', models.TextField(blank=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caixa.sessaocaixa')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='clientes.cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': [('usar_pdv', 'Pode finalizar vendas no PDV'), ('cancelar_venda', 'Pode cancelar vendas'), ('devolver_venda', 'Pode registrar devoluções'), ('ver_relatorios', 'Pode consultar relatórios'), ('ver_todas_vendas', 'Pode consultar vendas de todos os operadores'), ('dar_desconto', 'Pode conceder desconto')],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_nome', models.CharField(max_length=80)),
                ('dinheiro', models.BooleanField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recebido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('troco', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('forma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendas.formapagamento')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='vendas.venda')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=240)),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.peca')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='vendas.venda')),
            ],
        ),
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('quantidade', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo', models.TextField()),
                ('forma_nome', models.CharField(max_length=80)),
                ('dinheiro', models.BooleanField()),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caixa.sessaocaixa')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('forma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendas.formapagamento')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='vendas.itemvenda')),
            ],
            options={
                'verbose_name': 'devolução',
                'verbose_name_plural': 'devoluções',
                'constraints': [models.CheckConstraint(condition=models.Q(('quantidade__gt', 0), ('valor__gte', 0)), name='devolucao_valida')],
            },
        ),
        migrations.AddConstraint(
            model_name='venda',
            constraint=models.CheckConstraint(condition=models.Q(('total__gt', 0)), name='venda_total_positivo'),
        ),
        migrations.AddConstraint(
            model_name='venda',
            constraint=models.CheckConstraint(condition=models.Q(('desconto__gte', 0), ('desconto__lte', models.F('subtotal'))), name='venda_desconto_valido'),
        ),
        migrations.AddConstraint(
            model_name='venda',
            constraint=models.CheckConstraint(condition=models.Q(('total', django.db.models.expressions.CombinedExpression(models.F('subtotal'), '-', models.F('desconto')))), name='venda_total_consistente'),
        ),
        migrations.AddConstraint(
            model_name='pagamento',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0), ('troco__gte', 0)), name='pagamento_valores_validos'),
        ),
        migrations.AddConstraint(
            model_name='pagamento',
            constraint=models.CheckConstraint(condition=models.Q(('recebido', django.db.models.expressions.CombinedExpression(models.F('valor'), '+', models.F('troco')))), name='pagamento_troco_consistente'),
        ),
        migrations.AddConstraint(
            model_name='itemvenda',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='item_quantidade_positiva'),
        ),
        migrations.AddConstraint(
            model_name='itemvenda',
            constraint=models.UniqueConstraint(fields=('venda', 'peca'), name='item_peca_unica_por_venda'),
        ),
    ]
