# Generated by Django 5.2.17 on 2026-09-25 13:04

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0003_movimentocaixa_chave'),
        ('vendas', '0002_formas_iniciais'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoPromissoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('recebido', 'Recebimento'), ('abatido', 'Abatimento por cancelamento/devolução')], max_length=12)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('forma_nome', models.CharField(blank=True, max_length=80)),
                ('dinheiro', models.BooleanField(default=False)),
                ('motivo', models.CharField(blank=True, max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='NotaPromissoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emitida_em', models.DateField()),
                ('vencimento', models.DateField()),
                ('emitente', models.CharField(max_length=160)),
                ('documento', models.CharField(max_length=20)),
                ('endereco', models.TextField(blank=True)),
                ('beneficiario', models.CharField(max_length=160)),
                ('documento_beneficiario', models.CharField(blank=True, max_length=20)),
                ('local_emissao', models.CharField(max_length=160)),
                ('local_pagamento', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'nota promissória',
                'verbose_name_plural': 'notas promissórias',
                'ordering': ['vencimento', 'pk'],
            },
        ),
        migrations.AlterModelOptions(
            name='venda',
            options={'ordering': ['-pk'], 'permissions': [('editar_venda', 'Pode corrigir vendas concluídas'), ('receber_promissoria', 'Pode receber notas promissórias'), ('usar_pdv', 'Pode finalizar vendas no PDV'), ('cancelar_venda', 'Pode cancelar vendas'), ('devolver_venda', 'Pode registrar devoluções'), ('ver_relatorios', 'Pode consultar relatórios'), ('ver_todas_vendas', 'Pode consultar vendas de todos os operadores'), ('dar_desconto', 'Pode conceder desconto')]},
        ),
        migrations.RemoveConstraint(
            model_name='pagamento',
            name='pagamento_troco_consistente',
        ),
        migrations.AddField(
            model_name='devolucao',
            name='abatimento_promissoria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='promissoria',
            field=models.BooleanField(default=False, verbose_name='gera nota promissória (a receber)'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='promissoria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venda',
            name='substitui',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='substituta', to='vendas.venda'),
        ),
        migrations.AddConstraint(
            model_name='formapagamento',
            constraint=models.CheckConstraint(condition=models.Q(('dinheiro', True), ('promissoria', True), _negated=True), name='forma_promissoria_nao_dinheiro'),
        ),
        migrations.AddConstraint(
            model_name='pagamento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('promissoria', False), ('recebido', django.db.models.expressions.CombinedExpression(models.F('valor'), '+', models.F('troco')))), models.Q(('dinheiro', False), ('promissoria', True), ('recebido', 0), ('troco', 0)), _connector='OR'), name='pagamento_troco_consistente'),
        ),
        migrations.AddField(
            model_name='movimentopromissoria',
            name='caixa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caixa.sessaocaixa'),
        ),
        migrations.AddField(
            model_name='movimentopromissoria',
            name='forma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vendas.formapagamento'),
        ),
        migrations.AddField(
            model_name='movimentopromissoria',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notapromissoria',
            name='pagamento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='nota', to='vendas.pagamento'),
        ),
        migrations.AddField(
            model_name='movimentopromissoria',
            name='nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='vendas.notapromissoria'),
        ),
        migrations.AddConstraint(
            model_name='movimentopromissoria',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='movimento_promissoria_positivo'),
        ),
    ]
