# Generated by Django 5.2.17 on 2026-09-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_promissoria_inicial_e_historico'),
        ('core', '0003_configuracao_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='empresa_emissao',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.RunSQL(
            "CREATE TRIGGER proteger_empresa_emissao BEFORE UPDATE OF empresa_emissao ON vendas_venda "
            "FOR EACH ROW WHEN (OLD.empresa_emissao IS DISTINCT FROM NEW.empresa_emissao) "
            "EXECUTE FUNCTION pontocar_historico_imutavel()",
            "DROP TRIGGER proteger_empresa_emissao ON vendas_venda",
        ),
    ]
