# Generated by Django 5.2.17 on 2026-09-30 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
        ('estoque', '0004_alter_localizacao_codigo'),
        ('vendas', '0005_venda_empresa_emissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comercial.servico'),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='peca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estoque.peca'),
        ),
        migrations.AddConstraint(
            model_name='itemvenda',
            constraint=models.UniqueConstraint(fields=('venda', 'servico'), name='item_servico_unico_por_venda'),
        ),
        migrations.AddConstraint(
            model_name='itemvenda',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('peca__isnull', False), ('servico__isnull', True)), models.Q(('peca__isnull', True), ('servico__isnull', False)), _connector='OR'), name='item_venda_tipo'),
        ),
    ]
