# Generated by Django 5.2.17 on 2026-10-05 01:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0003_documento_condicao_pagamento_and_more'),
        ('estoque', '0004_alter_localizacao_codigo'),
        ('vendas', '0005_venda_empresa_emissao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFiscal',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('ativa', models.BooleanField(default=False, verbose_name='ativar operações fiscais')),
                ('ambiente', models.CharField(choices=[('homologacao', 'Homologação'), ('producao', 'Produção')], default='homologacao', max_length=12)),
                ('homologacao_validada', models.BooleanField(default=False)),
                ('producao_validada', models.BooleanField(default=False)),
                ('modelo_mercadorias', models.CharField(choices=[('55', 'NF-e'), ('65', 'NFC-e')], default='55', max_length=4)),
                ('cnpj', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'Informe 14 dígitos.')])),
                ('razao_social', models.CharField(max_length=200)),
                ('nome_fantasia', models.CharField(blank=True, max_length=200)),
                ('ie', models.CharField(blank=True, max_length=30, verbose_name='inscrição estadual')),
                ('im', models.CharField(blank=True, max_length=30, verbose_name='inscrição municipal')),
                ('crt', models.CharField(choices=[('1', 'Simples Nacional'), ('2', 'Simples: excesso sublimite'), ('3', 'Regime normal'), ('4', 'MEI')], default='1', max_length=1, verbose_name='CRT')),
                ('uf', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$')])),
                ('municipio_ibge', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\d{7}$', 'Informe 7 dígitos.')])),
                ('municipio', models.CharField(max_length=100)),
                ('logradouro', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Informe 8 dígitos.')])),
                ('telefone', models.CharField(blank=True, max_length=14)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('natureza_operacao', models.CharField(default='Venda de mercadorias', max_length=60)),
                ('csc_id', models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator('^\\d{1,6}$')])),
                ('csc_criptografado', models.BinaryField(blank=True)),
                ('certificado_criptografado', models.BinaryField(blank=True)),
                ('senha_a1_criptografada', models.BinaryField(blank=True)),
                ('certificado_valido_desde', models.DateTimeField(blank=True, editable=False, null=True)),
                ('certificado_valido_ate', models.DateTimeField(blank=True, editable=False, null=True)),
                ('certificado_fingerprint', models.CharField(blank=True, editable=False, max_length=64)),
                ('endpoints', models.JSONField(blank=True, default=dict)),
                ('parametros_nfse', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'permissions': [('configurar_fiscal', 'Pode configurar o módulo fiscal')],
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='fiscal_config_unica')],
            },
        ),
        migrations.CreateModel(
            name='DocumentoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('idempotencia', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('modelo', models.CharField(choices=[('55', 'NF-e'), ('65', 'NFC-e'), ('nfse', 'NFS-e')], max_length=4)),
                ('ambiente', models.CharField(choices=[('homologacao', 'Homologação'), ('producao', 'Produção')], max_length=12)),
                ('serie', models.PositiveIntegerField()),
                ('numero', models.PositiveIntegerField()),
                ('chave_acesso', models.CharField(blank=True, db_index=True, max_length=50)),
                ('identificador_dps', models.CharField(blank=True, max_length=80)),
                ('protocolo', models.CharField(blank=True, max_length=80)),
                ('recibo', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('nao_solicitada', 'Não solicitada'), ('pendente', 'Pendente'), ('processando', 'Processando'), ('autorizada', 'Autorizada'), ('rejeitada', 'Rejeitada'), ('contingencia', 'Contingência'), ('cancelamento_pendente', 'Cancelamento pendente'), ('cancelada', 'Cancelada'), ('erro_tecnico', 'Erro técnico')], db_index=True, default='nao_solicitada', max_length=30)),
                ('emitido_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('autorizado_em', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('snapshot', models.JSONField(default=dict, editable=False)),
                ('xml_assinado', models.TextField(blank=True, editable=False)),
                ('xml_autorizado', models.TextField(blank=True, editable=False)),
                ('qr_code', models.TextField(blank=True, editable=False)),
                ('codigo_resposta', models.CharField(blank=True, max_length=20)),
                ('mensagem', models.CharField(blank=True, max_length=500)),
                ('transmissao_incerta', models.BooleanField(default=False, editable=False)),
                ('processamento_iniciado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fiscal.configuracaofiscal')),
                ('ordem_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_fiscais', to='comercial.documento')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_fiscais', to='vendas.venda')),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': [('emitir_fiscal', 'Pode solicitar e transmitir documentos fiscais'), ('cancelar_fiscal', 'Pode solicitar cancelamentos fiscais'), ('consultar_fiscal', 'Pode consultar documentos fiscais e XML'), ('inutilizar_fiscal', 'Pode inutilizar numeração fiscal')],
            },
        ),
        migrations.CreateModel(
            name='EventoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipo', models.CharField(choices=[('cancelamento', 'Cancelamento'), ('inutilizacao', 'Inutilização'), ('consulta', 'Consulta'), ('contingencia', 'Contingência')], max_length=20)),
                ('idempotencia', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('nao_solicitada', 'Não solicitada'), ('pendente', 'Pendente'), ('processando', 'Processando'), ('autorizada', 'Autorizada'), ('rejeitada', 'Rejeitada'), ('contingencia', 'Contingência'), ('cancelamento_pendente', 'Cancelamento pendente'), ('cancelada', 'Cancelada'), ('erro_tecnico', 'Erro técnico')], default='pendente', max_length=30)),
                ('ambiente', models.CharField(choices=[('homologacao', 'Homologação'), ('producao', 'Produção')], max_length=12)),
                ('modelo', models.CharField(choices=[('55', 'NF-e'), ('65', 'NFC-e'), ('nfse', 'NFS-e')], max_length=4)),
                ('serie', models.PositiveIntegerField(default=1)),
                ('numero_inicial', models.PositiveIntegerField(blank=True, null=True)),
                ('numero_final', models.PositiveIntegerField(blank=True, null=True)),
                ('ano', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('justificativa', models.CharField(blank=True, max_length=255)),
                ('protocolo', models.CharField(blank=True, max_length=80)),
                ('xml', models.TextField(blank=True, editable=False)),
                ('codigo_resposta', models.CharField(blank=True, max_length=20)),
                ('mensagem', models.CharField(blank=True, max_length=500)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fiscal.configuracaofiscal')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='fiscal.documentofiscal')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='ParametroProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ncm', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Informe 8 dígitos.')])),
                ('cfop', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Informe 4 dígitos.')])),
                ('origem', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='0', max_length=1)),
                ('unidade', models.CharField(default='UN', max_length=6)),
                ('cest', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^\\d{7}$', 'Informe 7 dígitos.')])),
                ('csosn', models.CharField(default='102', max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$', 'Informe 3 dígitos.')])),
                ('cst_icms', models.CharField(default='00', max_length=2, validators=[django.core.validators.RegexValidator('^\\d{2}$', 'Informe 2 dígitos.')])),
                ('aliquota_icms', models.DecimalField(decimal_places=4, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cst_pis', models.CharField(default='07', max_length=2, validators=[django.core.validators.RegexValidator('^\\d{2}$', 'Informe 2 dígitos.')])),
                ('aliquota_pis', models.DecimalField(decimal_places=4, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cst_cofins', models.CharField(default='07', max_length=2, validators=[django.core.validators.RegexValidator('^\\d{2}$', 'Informe 2 dígitos.')])),
                ('aliquota_cofins', models.DecimalField(decimal_places=4, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tributos_adicionais', models.JSONField(blank=True, default=dict, help_text='Grupos tributários do leiaute oficial, inclusive IBS/CBS quando aplicáveis.')),
                ('peca', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='parametro_fiscal', to='estoque.peca')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParametroServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('item_lista_lc116', models.CharField(max_length=10)),
                ('codigo_tributacao_nacional', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Informe 6 dígitos.')])),
                ('codigo_tributacao_municipal', models.CharField(blank=True, max_length=20)),
                ('nbs', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'Informe 9 dígitos.')])),
                ('aliquota_iss', models.DecimalField(decimal_places=4, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('iss_retido', models.BooleanField(default=False)),
                ('municipio_incidencia', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\d{7}$', 'Informe 7 dígitos.')])),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('servico', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='parametro_fiscal', to='comercial.servico')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SequenciaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('55', 'NF-e'), ('65', 'NFC-e'), ('nfse', 'NFS-e')], max_length=4)),
                ('ambiente', models.CharField(choices=[('homologacao', 'Homologação'), ('producao', 'Produção')], max_length=12)),
                ('serie', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
                ('proximo_numero', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)])),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fiscal.configuracaofiscal')),
            ],
        ),
        migrations.CreateModel(
            name='TentativaTransmissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('operacao', models.CharField(max_length=30)),
                ('pedido_sha256', models.CharField(blank=True, max_length=64)),
                ('resposta', models.TextField(blank=True, editable=False)),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('mensagem', models.CharField(blank=True, max_length=500)),
                ('erro_tecnico', models.BooleanField(default=False)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tentativas', to='fiscal.documentofiscal')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tentativas', to='fiscal.eventofiscal')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentofiscal',
            constraint=models.UniqueConstraint(fields=('configuracao', 'modelo', 'ambiente', 'serie', 'numero'), name='fiscal_numero_unico'),
        ),
        migrations.AddConstraint(
            model_name='documentofiscal',
            constraint=models.UniqueConstraint(condition=models.Q(('venda__isnull', False)), fields=('venda', 'modelo', 'ambiente'), name='fiscal_venda_modelo_unico'),
        ),
        migrations.AddConstraint(
            model_name='documentofiscal',
            constraint=models.UniqueConstraint(condition=models.Q(('ordem_servico__isnull', False)), fields=('ordem_servico', 'modelo', 'ambiente'), name='fiscal_os_modelo_unico'),
        ),
        migrations.AddConstraint(
            model_name='documentofiscal',
            constraint=models.CheckConstraint(condition=models.Q(('venda__isnull', False), ('ordem_servico__isnull', False), _connector='OR'), name='fiscal_documento_origem'),
        ),
        migrations.AddConstraint(
            model_name='documentofiscal',
            constraint=models.CheckConstraint(condition=models.Q(('numero__gte', 1), ('serie__gte', 1), ('total__gt', 0)), name='fiscal_documento_valores'),
        ),
        migrations.AddConstraint(
            model_name='eventofiscal',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'cancelamento')), fields=('documento', 'tipo'), name='fiscal_cancelamento_unico'),
        ),
        migrations.AddConstraint(
            model_name='sequenciafiscal',
            constraint=models.UniqueConstraint(fields=('configuracao', 'modelo', 'ambiente', 'serie'), name='fiscal_sequencia_unica'),
        ),
        migrations.AddConstraint(
            model_name='sequenciafiscal',
            constraint=models.CheckConstraint(condition=models.Q(('proximo_numero__gte', 1), ('serie__gte', 1), ('serie__lte', 999)), name='fiscal_sequencia_valida'),
        ),
    ]
