# Generated by Django 5.2.17 on 2026-10-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaofiscal',
            name='csc_ambiente',
            field=models.CharField(choices=[('homologacao', 'Homologação'), ('producao', 'Produção')], default='homologacao', editable=False, max_length=12),
        ),
        migrations.AddField(
            model_name='configuracaofiscal',
            name='qr_code_versao',
            field=models.CharField(choices=[('2', '2.00 (CSC)'), ('3', '3.00')], default='3', max_length=1),
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='tipo_emissao',
            field=models.CharField(choices=[('1', 'Normal'), ('9', 'Contingência offline NFC-e')], default='1', editable=False, max_length=1),
        ),
    ]
