# Generated by Django 5.2.17 on 2026-09-25 03:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('codigo', models.CharField(max_length=40, unique=True, verbose_name='código interno')),
                ('marca', models.CharField(db_index=True, max_length=80)),
                ('modelo', models.CharField(db_index=True, max_length=120)),
                ('versao', models.CharField(blank=True, max_length=120, verbose_name='versão')),
                ('ano_fabricacao', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='ano de fabricação')),
                ('ano_modelo', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='ano modelo')),
                ('motor', models.CharField(blank=True, max_length=80)),
                ('combustivel', models.CharField(blank=True, max_length=40, verbose_name='combustível')),
                ('cambio', models.CharField(blank=True, max_length=60, verbose_name='câmbio')),
                ('cor', models.CharField(blank=True, max_length=50)),
                ('data_entrada', models.DateField(verbose_name='data de entrada')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('situacao', models.CharField(choices=[('recebido', 'Recebido'), ('desmontagem', 'Em desmontagem'), ('desmontado', 'Desmontado'), ('inativo', 'Inativo')], default='recebido', max_length=20, verbose_name='situação')),
            ],
            options={
                'verbose_name': 'veículo de origem',
                'verbose_name_plural': 'veículos de origem',
                'ordering': ['-data_entrada', 'codigo'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ano_fabricacao__isnull', True), ('ano_fabricacao__range', (1900, 2100)), _connector='OR'), name='veiculo_ano_fabricacao_valido'), models.CheckConstraint(condition=models.Q(('ano_modelo__isnull', True), ('ano_modelo__range', (1900, 2100)), _connector='OR'), name='veiculo_ano_modelo_valido')],
            },
        ),
    ]
