# Generated by Django 5.2.17 on 2026-09-25 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('marca', models.CharField(max_length=80)),
                ('nome', models.CharField(max_length=120, verbose_name='modelo')),
            ],
            options={
                'verbose_name': 'modelo de veículo',
                'verbose_name_plural': 'marcas e modelos de veículos',
                'ordering': ['marca', 'nome'],
                'constraints': [models.UniqueConstraint(fields=('marca', 'nome'), name='modelo_unico_por_marca')],
            },
        ),
    ]
