# Generated by Django 5.2.17 on 2026-09-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0003_catalogo_inicial'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE SEQUENCE veiculos_veiculo_codigo_seq",
            "DROP SEQUENCE veiculos_veiculo_codigo_seq",
        ),
        migrations.RunSQL(
            "SELECT setval('veiculos_veiculo_codigo_seq', COALESCE((SELECT MAX(substring(codigo from '[0-9]+$')::bigint) FROM veiculos_veiculo WHERE codigo ~ '^VEI-[0-9]+$'), 0) + 1, false)",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=40, unique=True, verbose_name='código interno'),
        ),
    ]
