# Generated by Django 5.2.17 on 2026-09-30 04:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caixa', '0003_movimentocaixa_chave'),
        ('clientes', '0001_initial'),
        ('estoque', '0004_alter_localizacao_codigo'),
        ('vendas', '0005_venda_empresa_emissao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipo', models.CharField(choices=[('orcamento', 'Orçamento'), ('os', 'Ordem de serviço')], max_length=12)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('vencido', 'Vencido'), ('convertido', 'Convertido'), ('aberta', 'Aberta'), ('andamento', 'Em andamento'), ('aguardando', 'Aguardando peça'), ('finalizada', 'Finalizada'), ('entregue', 'Entregue'), ('cancelada', 'Cancelada')], max_length=12)),
                ('veiculo', models.CharField(blank=True, max_length=200, verbose_name='veículo / marca e modelo')),
                ('placa', models.CharField(blank=True, max_length=12)),
                ('ano', models.CharField(blank=True, max_length=20)),
                ('km', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM de entrada')),
                ('combustivel', models.CharField(blank=True, max_length=60, verbose_name='combustível')),
                ('validade', models.DateField(blank=True, null=True)),
                ('previsao', models.DateField(blank=True, null=True, verbose_name='previsão de conclusão')),
                ('conclusao', models.DateField(blank=True, null=True, verbose_name='data de conclusão')),
                ('responsavel', models.CharField(blank=True, max_length=160, verbose_name='responsável / técnico')),
                ('relato', models.TextField(blank=True, verbose_name='relato do cliente')),
                ('diagnostico', models.TextField(blank=True, verbose_name='diagnóstico')),
                ('solicitado', models.TextField(blank=True, verbose_name='serviço solicitado')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('condicoes', models.TextField(blank=True, verbose_name='condições')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_registros', to='clientes.cliente')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('origem', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordem_gerada', to='comercial.documento')),
                ('venda', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documento_origem', to='vendas.venda')),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': [('converter_documento', 'Pode converter orçamento e OS')],
            },
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('descricao', models.CharField(max_length=240, verbose_name='descrição')),
                ('origem', models.CharField(default='Manual', max_length=80)),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vencimento', models.DateField()),
                ('cancelada', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_registros', to='clientes.cliente')),
                ('venda', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conta_receber', to='vendas.venda')),
                ('os', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comercial.documento')),
            ],
            options={
                'ordering': ['vencimento', 'pk'],
                'permissions': [('receber_conta', 'Pode registrar recebimentos')],
            },
        ),
        migrations.CreateModel(
            name='Recebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('forma_nome', models.CharField(max_length=80)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos', to='comercial.contareceber')),
                ('forma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendas.formapagamento')),
                ('movimento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='caixa.movimentocaixa')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=160)),
                ('categoria', models.CharField(blank=True, max_length=100, verbose_name='categoria/tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('valor_padrao', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor padrão')),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'ordering': ['nome', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valor_padrao__gte', 0)), name='servico_valor_positivo')],
            },
        ),
        migrations.CreateModel(
            name='ItemDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=240)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor unitário')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='comercial.documento')),
                ('peca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estoque.peca')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comercial.servico')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.CheckConstraint(condition=models.Q(('desconto__gte', 0)), name='documento_desconto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='contareceber',
            constraint=models.CheckConstraint(condition=models.Q(('valor_original__gt', 0)), name='receber_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='recebimento',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='recebimento_positivo'),
        ),
        migrations.AddConstraint(
            model_name='itemdocumento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('peca__isnull', False), ('servico__isnull', True)), models.Q(('peca__isnull', True), ('servico__isnull', False)), _connector='OR'), name='documento_item_tipo'),
        ),
        migrations.AddConstraint(
            model_name='itemdocumento',
            constraint=models.CheckConstraint(condition=models.Q(('preco__gte', 0), ('quantidade__gt', 0)), name='documento_item_valor'),
        ),
    ]
