# Generated by Django 5.2.17 on 2026-09-30 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_proteger_recebimentos'),
        ('vendas', '0006_itemvenda_servico_alter_itemvenda_peca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='condicao_pagamento',
            field=models.CharField(choices=[('avista', 'À vista'), ('parcelado', 'Parcelado')], default='avista', max_length=20, verbose_name='condição de pagamento'),
        ),
        migrations.AddField(
            model_name='documento',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_comerciais', to='vendas.formapagamento', verbose_name='forma de pagamento'),
        ),
        migrations.AddField(
            model_name='documento',
            name='parcelas',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='parcelas'),
        ),
        migrations.AddField(
            model_name='documento',
            name='primeiro_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='primeiro vencimento'),
        ),
    ]
