# Generated by Django 5.2.17 on 2026-10-06 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_documento_condicao_pagamento_and_more'),
        ('vendas', '0007_boleto_parcelado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='lancamento_chave',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ParcelaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_financeiras', to='comercial.contareceber')),
                ('forma_prevista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vendas.formapagamento')),
            ],
            options={
                'ordering': ['numero'],
                'constraints': [models.UniqueConstraint(fields=('conta', 'numero'), name='receber_parcela_unica'), models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='receber_parcela_positiva')],
            },
        ),
    ]
