# Generated by Django 5.2.17 on 2026-09-25 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('saldo_informado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('saldo_esperado_fechamento', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'sessão de caixa',
                'verbose_name_plural': 'sessões de caixa',
                'ordering': ['-pk'],
                'permissions': [('operar_caixa', 'Pode abrir e operar o próprio caixa'), ('ver_todos_caixas', 'Pode consultar todos os caixas')],
            },
        ),
        migrations.CreateModel(
            name='MovimentoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('venda', 'Venda'), ('sangria', 'Sangria'), ('suprimento', 'Suprimento'), ('estorno', 'Estorno')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('afeta_saldo', models.BooleanField(default=True)),
                ('descricao', models.CharField(max_length=240)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'movimentação de caixa',
                'verbose_name_plural': 'movimentações de caixa',
                'ordering': ['-pk'],
            },
        ),
    ]
