# Generated by Django 5.2.17 on 2026-09-25 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caixa', '0001_initial'),
        ('vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentocaixa',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vendas.venda'),
        ),
        migrations.AddField(
            model_name='sessaocaixa',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='sessao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='caixa.sessaocaixa'),
        ),
        migrations.AddConstraint(
            model_name='sessaocaixa',
            constraint=models.UniqueConstraint(condition=models.Q(('fechado_em__isnull', True)), fields=('operador',), name='um_caixa_aberto_por_operador'),
        ),
        migrations.AddConstraint(
            model_name='sessaocaixa',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_inicial__gte', 0)), name='caixa_abertura_positiva'),
        ),
        migrations.AddConstraint(
            model_name='sessaocaixa',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_informado__isnull', True), ('saldo_informado__gte', 0), _connector='OR'), name='caixa_informado_positivo'),
        ),
    ]
