# Generated by Django 5.2.17 on 2026-09-25 04:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentocaixa',
            name='chave',
            field=models.UUIDField(editable=False, unique=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimentocaixa',
            name='chave',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, null=True),
        ),
    ]
