from decimal import Decimal

from django.core.management.base import BaseCommand
from django.db import transaction

from comercial.models import Servico


SERVICOS = [
    "Alinhamento de direção",
    "Alinhamento de faróis",
    "Alinhamento de rodas",
    "Aplicação de película automotiva",
    "Aplicação de silicone e vedação",
    "Balanceamento de rodas",
    "Calibragem de pneus",
    "Carga de bateria",
    "Carga de gás do ar-condicionado",
    "Codificação de chave",
    "Configuração de central multimídia",
    "Configuração de controle remoto",
    "Configuração de módulo eletrônico",
    "Conserto de alternador",
    "Conserto de chicote elétrico",
    "Conserto de motor de partida",
    "Conserto de trava elétrica",
    "Conserto de vidro elétrico",
    "Cristalização de para-brisa",
    "Diagnóstico automotivo",
    "Diagnóstico com scanner",
    "Diagnóstico de ar-condicionado",
    "Diagnóstico de bateria",
    "Diagnóstico de falha elétrica",
    "Diagnóstico de injeção eletrônica",
    "Diagnóstico eletrônico",
    "Higienização de ar-condicionado",
    "Instalação",
    "Instalação de acessórios automotivos",
    "Instalação de aerofólio",
    "Instalação de alarme",
    "Instalação de alto-falante",
    "Instalação de amplificador",
    "Instalação de antena",
    "Instalação de apoio de braço",
    "Instalação de barra de LED",
    "Instalação de buzina",
    "Instalação de câmera 360°",
    "Instalação de câmera de ré",
    "Instalação de câmera veicular",
    "Instalação de capa de banco",
    "Instalação de capota marítima",
    "Instalação de central multimídia",
    "Instalação de climatizador",
    "Instalação de engate",
    "Instalação de estribo",
    "Instalação de farol auxiliar",
    "Instalação de farol de milha",
    "Instalação de friso",
    "Instalação de GPS",
    "Instalação de iluminação interna",
    "Instalação de lâmpada",
    "Instalação de lâmpada LED",
    "Instalação de lanterna",
    "Instalação de módulo amplificador",
    "Instalação de módulo de vidro",
    "Instalação de película",
    "Instalação de porta-celular",
    "Instalação de rádio",
    "Instalação de rack de teto",
    "Instalação de rastreador",
    "Instalação de retrovisor",
    "Instalação de santo-antônio",
    "Instalação de sensor de estacionamento",
    "Instalação de sistema de som",
    "Instalação de spoiler",
    "Instalação de subwoofer",
    "Instalação de trava elétrica",
    "Instalação de vidro elétrico",
    "Instalação elétrica de acessórios",
    "Limpeza de bicos injetores",
    "Limpeza de corpo de borboleta",
    "Limpeza de sistema de arrefecimento",
    "Manutenção",
    "Manutenção de ar-condicionado",
    "Manutenção elétrica",
    "Manutenção preventiva",
    "Montagem de acessórios",
    "Montagem de pneus",
    "Reparo",
    "Reparo de ar-condicionado",
    "Reparo de chicote elétrico",
    "Reparo de farol",
    "Reparo de lanterna",
    "Reparo de para-brisa",
    "Reparo de pneu",
    "Reparo de sistema elétrico",
    "Reparo de vidro elétrico",
    "Revisão automotiva",
    "Revisão de iluminação",
    "Revisão elétrica",
    "Sangria do sistema de freio",
    "Scanner automotivo",
    "Substituição de amortecedor",
    "Substituição de bandeja",
    "Substituição de bateria",
    "Substituição de bieleta",
    "Substituição de bobina de ignição",
    "Substituição de bomba de combustível",
    "Substituição de bomba d'água",
    "Substituição de braço do limpador",
    "Substituição de cabo de embreagem",
    "Substituição de correia",
    "Substituição de correia dentada",
    "Substituição de correia do alternador",
    "Substituição de coxim",
    "Substituição de disco de freio",
    "Substituição de embreagem",
    "Substituição de farol",
    "Substituição de filtro de ar",
    "Substituição de filtro de cabine",
    "Substituição de filtro de combustível",
    "Substituição de filtro de óleo",
    "Substituição de fusível",
    "Substituição de lâmpada",
    "Substituição de lanterna",
    "Substituição de mangueira",
    "Substituição de óleo do câmbio",
    "Substituição de palheta do limpador",
    "Substituição de pastilha de freio",
    "Substituição de pivô",
    "Substituição de rolamento",
    "Substituição de sensor",
    "Substituição de terminal de direção",
    "Substituição de vela de ignição",
    "Substituição de vidro",
    "Suporte",
    "Teste de alternador",
    "Teste de bateria",
    "Teste de carga",
    "Teste de motor de partida",
    "Teste do sistema elétrico",
    "Troca de amortecedor",
    "Troca de bateria",
    "Troca de bieleta",
    "Troca de bobina",
    "Troca de bomba de combustível",
    "Troca de bomba d'água",
    "Troca de braço do limpador",
    "Troca de cabo de embreagem",
    "Troca de correia",
    "Troca de correia dentada",
    "Troca de correia Poly-V",
    "Troca de coxim",
    "Troca de disco de freio",
    "Troca de embreagem",
    "Troca de farol",
    "Troca de filtro de ar",
    "Troca de filtro de cabine",
    "Troca de filtro de combustível",
    "Troca de filtro de óleo",
    "Troca de fluido de freio",
    "Troca de fluido de transmissão",
    "Troca de fusível",
    "Troca de lâmpada",
    "Troca de lanterna",
    "Troca de líquido de arrefecimento",
    "Troca de óleo",
    "Troca de óleo de câmbio",
    "Troca de óleo de diferencial",
    "Troca de palheta do limpador",
    "Troca de pastilha de freio",
    "Troca de peça",
    "Troca de pivô",
    "Troca de pneu",
    "Troca de rolamento",
    "Troca de sensor",
    "Troca de terminal de direção",
    "Troca de vela",
    "Troca de vidro",
    "Troca e instalação de acessórios",
    "Vedação de farol",
    "Vedação de lanterna",
    "Outros",
]


class Command(BaseCommand):
    help = "Cadastra a lista padrão de serviços do REGISTER sem duplicar existentes."

    @transaction.atomic
    def handle(self, *args, **options):
        criados = 0
        existentes = 0

        for nome in SERVICOS:
            servico = Servico.objects.filter(nome__iexact=nome).first()

            if servico:
                existentes += 1
                continue

            Servico.objects.create(
                nome=nome,
                valor_padrao=Decimal("0.00"),
                ativo=True,
            )
            criados += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Concluído: {criados} serviços criados e "
                f"{existentes} já existentes preservados."
            )
        )